admission_exam_db/urls.py
from django.urls import path, include

from . import views

app_name = "admission_exam_db"
urlpatterns = [
    path("", views.index, name="index"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("user/", views.user, name="user"),
    path("student/", views.student, name="student"),
    path("student/<int:student_id>", views.student_detail, name="student_detail"),
    path("upload_university_faculty", views.upload_university_faculty, name="upload_university_faculty"),
    path("download_template_csv/<str:file_kind>", views.download_template_csv, name="download_template_csv"),
    path("download_data", views.download_data, name="download_data"),
    path("download_data/csv/<str:file_kind>", views.download_data_csv, name="download_data_csv"),
    path("upload_student", views.upload_student, name="upload_student"),
    path("upload_student_admission_exam", views.upload_student_admission_exam, name="upload_student_admission_exam"),
    path("upload_user", views.upload_user, name="upload_user"),
    path("upload_success", views.upload_success, name="upload_success"),
    path("student/<int:student_id>/create_student_admission_exam", views.create_student_admission_exam, name="create_student_admission_exam"),
    path("student/<int:student_id>/<int:student_admission_exam_id>", views.edit_student_admission_exam, name="edit_student_admission_exam"),
    path("student/<int:student_id>/<int:student_admission_exam_id>/delete", views.delete_student_admission_exam, name="delete_student_admission_exam"),
    path("admission_exam/", views.admission_exam, name="admission_exam"),
    path("passed_exam_count/", views.passed_exam_count, name="passed_exam_count"),
    path("passed_exam_by_university/<str:university>/<str:exam_year>/", views.passed_exam_by_university, name="passed_exam_by_university"),
    path("api/university_faculty", views.university_faculty_autocomplete, name="university_faculty_autocomplete"),
]

schoolapps/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

# envファイル読み込み用
from dotenv import load_dotenv
load_dotenv()# .envファイル読み込み
import os


urlpatterns = [
    path('admin/', admin.site.urls),
    path('admission_exam_db/', include("admission_exam_db.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\

if settings.DEBUG:
    from debug_toolbar.toolbar import debug_toolbar_urls
    urlpatterns = [
        *urlpatterns,
    ] + debug_toolbar_urls()

admission_exam_db/models.py
from django.db import models
from django.core import validators
import logging
import datetime

logger = logging.getLogger('django')


class Student(models.Model):
    student_id = models.CharField(max_length=7, primary_key=True)
    homeroom_class = models.CharField(max_length=1)
    attendance_number = models.CharField(max_length=2)
    family_name = models.CharField(max_length=30)
    given_name = models.CharField(max_length=30)
    family_name_kana = models.CharField(max_length=30)
    given_name_kana = models.CharField(max_length=30)
    graduation_year = models.CharField(max_length=4)
    gender = models.CharField( # 志望
        max_length=1,
        choices=[
            ('M', '男性'),
            ('F', '女性')
        ],
        null=True,
        blank=True
    )

    def __str__(self):
        return " ".join([self.family_name, self.given_name])

class UniversityFaculty(models.Model):
    university_faculty_code = models.CharField(max_length=5, primary_key=True)# 記入用大学コード(５桁)
    university_name = models.CharField(max_length=20)  # 大学短縮名
    faculty_name = models.CharField(max_length=20) # 学部短縮名
    department_name = models.CharField(max_length=20) # 学科短縮名
    display_name = models.CharField(max_length=50) # 表示名
    faculty_system_midstream_name = models.CharField(max_length=20) # 学部系統(中系統)名称
    faculty_system_field_code = models.CharField(max_length=4) # 学部系統(分野)コード
    faculty_system_field_name = models.CharField(max_length=20) # 学部系統(分野)名称

    def __str__(self):
        return self.display_name

class StudentAdmissionExam(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    university_faculty = models.ForeignKey(UniversityFaculty, on_delete=models.CASCADE)
    year_to_take = models.CharField(max_length=4)
    PREFERENCE_CHOICES = [
        ('A1','受かったら必ず入学する第1志望'),
        ('A2','受かったら必ず入学する第2志望'),
        ('A3','受かったら必ず入学する第3志望'),
        ('A4','受かったら必ず入学する第4志望'),
        ('A5','受かったら必ず入学する第5志望'),
        ('A6','受かったら必ず入学する第6志望'),
        ('A7','受かったら必ず入学する第7志望'),
        ('A8','受かったら必ず入学する第8志望'),
        ('A9','受かったら必ず入学する第9志望'),
        ('A10','受かったら必ず入学する第10志望'),
        ('B','状況によって入学を検討する'),
        ('C','受かっても入学しない'),
    ]
    PASSED_CHOICES = [
        ('AE','合格（入学）'),
        ('AN','合格（入学せず）'),
        ('ASE','合格（特待、入学）'),
        ('ASN','合格（特待、入学せず）'),
        ('OP','他志望で合格'),
        ('AAE','追加合格（不合格から合格）して入学'),
        ('AAN','追加合格（不合格から合格）して入学せず'),
        ('SAE','補欠合格（補欠から合格）して入学'),
        ('SAN','補欠合格（補欠から合格）して入学せず'),
    ]
    REJECTED_CHOICES = [
        ('R','不合格'),# Rejectedのつもりやったけど, Failedの方が自然やったみたい.更新しよか迷う.
        ('FASN','前期合格で後期受験せず'),
        ('1A2N','1次合格2次受験せず'),
        ('1A2R','1次合格2次不合格'),
        ('1R','1次不合格'),
        ('CN','共通テスト後出願せず'),
        ('N','受験せず（受験番号あり）'),
        ('NA','出願せず（受験番号なし）'),
        ('REAN','推薦、総合型で合格したので受験せず'),
    ]
    YET_CHOICES = [
        ('S','補欠'),
    ] + [('None', 'None')]
    RESULT_CHOICES = PASSED_CHOICES + REJECTED_CHOICES + YET_CHOICES

    RESULT_STATUS_CHOICES = [
        ('P','合格'),
        ('R','不合格'),
        ('Y','未定'),
    ]
    preference = models.CharField( # 志望
        max_length=3,
        choices=PREFERENCE_CHOICES,
        null=False,
        blank=False
    )
    result = models.CharField(
        max_length=4,
        choices=RESULT_CHOICES,
        null=True,
        blank=True
    )
    result_status = models.CharField(
        max_length=1,
        choices=RESULT_STATUS_CHOICES,
        null=True,
        blank=True
    )
    info = models.CharField( #備考
        max_length=200,
        null=True,
        blank=True
    )

    def __str__(self):
        return " ".join([self.student.family_name, self.student.given_name]) + ": " + self.university_faculty.display_name

    def save(self, user=None, *args, **kwargs):
        is_new = self.pk is None  # 既存のデータであればpkが存在

        # result_categoryの設定
        if self.result in [key for key, _ in self.PASSED_CHOICES]:
            self.result_status = 'P'
        elif self.result in [key for key, _ in self.REJECTED_CHOICES]:
            self.result_status = 'R'
        elif self.result in [key for key, _ in self.YET_CHOICES]:
            self.result_status = 'Y'
        else:
            pass # Exceptionをthrowした方が良さそう

        super().save(*args, **kwargs)

        if is_new:
            logger.info(f"Created New Object: {self}, New Object ID Assigned: {self.pk}, Created By User ID: {user.id if user else 'Anonymous'}")
        else:
            logger.info(f"Updated Object: {self}, Object ID: {self.pk}, Updated By User ID: {user.id if user else 'Anonymous'}")
    def delete(self, user=None, *args, **kwargs):
        object_id = self.pk
        super().delete(*args, **kwargs)

        # ログに記録
        logger.info(f"Deleted Object: {self.__class__.__name__}, Object ID: {object_id}, Deleted By User ID: {user.id if user else 'Anonymous'}")

admission_exam_db/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, StreamingHttpResponse, JsonResponse
from .forms import UniversityFacultyCSVUploadForm, StudentCSVUploadForm, UserCSVUploadForm, StudentAdmissionExamForm, StudentAdmissionExamCSVUploadForm

from .models import Student, UniversityFaculty, StudentAdmissionExam
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib import messages

from django.db.models import Q, F, Count

import csv
import io
import logging
import datetime

logger = logging.getLogger('django')


def is_admin(user):
    return user.is_superuser

def is_editor(user):
    if user.groups.filter(name="editor").exists() or user.is_superuser:
        return True
    else:
        return False

@login_required
def index(request):
    context = {
        'nbar': 'home',
    }
    return render(request, "admission_exam_db/index.html", context)

@login_required
def student(request):
    student_list = Student.objects.order_by("-graduation_year", "homeroom_class", "attendance_number")
    context ={
        'nbar': 'student',
        'student_list': student_list,
    }
    return render(request, "admission_exam_db/student.html", context)

@login_required
def admission_exam(request):
    admission_exam_list = StudentAdmissionExam.objects.order_by("-year_to_take", "university_faculty_id")
    passed_choices = [ {"key":key, "value":value} for key, value in StudentAdmissionExam.PASSED_CHOICES ]
    rejected_choices = [ {"key":key, "value":value} for key, value in StudentAdmissionExam.REJECTED_CHOICES ]
    yet_choices = [ {"key":key, "value":value} for key, value in StudentAdmissionExam.YET_CHOICES ]
    context ={
        'nbar': 'admission_exam',
        'admission_exam_list': admission_exam_list,
        'passed_choices': passed_choices,
        'rejected_choices': rejected_choices,
        'yet_choices': yet_choices,
    }
    return render(request, "admission_exam_db/admission_exam.html", context)

@login_required
def passed_exam_count(request):
    student_admission_exam = StudentAdmissionExam.objects.filter(result_status="P").all()
    years = sorted(list({ dic["year_to_take"] for dic in student_admission_exam.values("year_to_take") }), reverse=True)
    passed_exam_count_table = {
        year: {}
        for year in years
    }

    for year in years:
        university_faculty_list = UniversityFaculty.objects.filter(studentadmissionexam__year_to_take=year, studentadmissionexam__result_status="P").values("studentadmissionexam__year_to_take", "university_name", "faculty_name").annotate(passed_exam_count=Count("studentadmissionexam", distinct=True), passed_exam_count_by_graduates=Count("studentadmissionexam", filter=Q(studentadmissionexam__student__graduation_year__lt=F("studentadmissionexam__year_to_take")), distinct=True)).filter(passed_exam_count__gt=0)# １対多の多側は小文字らしい.
        university_name_list = university_faculty_list.values("university_name").order_by("university_faculty_code")
        passed_exam_count_table[year] = {
            university_name['university_name']: {}
            for university_name in university_name_list
        }
        for faculty in university_faculty_list:
            passed_exam_count_table[year][faculty["university_name"]][faculty["faculty_name"]] = {'total':faculty["passed_exam_count"], 'graduates':faculty["passed_exam_count_by_graduates"]}

    context ={
        'passed_exam_count_table': passed_exam_count_table,
        'nbar': 'passed_exam_count',
    }
    return render(request, "admission_exam_db/passed_exam_count.html", context)

@login_required
def passed_exam_by_university(request, exam_year, university):
    admission_exam_list = StudentAdmissionExam.objects.filter(university_faculty__university_name=university, year_to_take=exam_year, result_status="P").order_by("university_faculty__university_faculty_code", "-student__graduation_year")
    context ={
        'nbar': 'passed_exam_count',
        'exam_year': exam_year,
        'university': university,
        'admission_exam_list': admission_exam_list,
    }
    return render(request, "admission_exam_db/passed_exam_by_university.html", context)

@login_required
def student_detail(request, student_id):
    student = get_object_or_404(Student, student_id=student_id)

    prev_student = Student.objects.filter(
        Q(homeroom_class__lt=student.homeroom_class) |
        Q(homeroom_class=student.homeroom_class, attendance_number__lt=student.attendance_number)
    ).order_by('-homeroom_class', '-attendance_number').first()

    next_student = Student.objects.filter(
        Q(homeroom_class__gt=student.homeroom_class) |
        Q(homeroom_class=student.homeroom_class, attendance_number__gt=student.attendance_number)
    ).order_by('homeroom_class', 'attendance_number').first()

    student_admission_exam_list = StudentAdmissionExam.objects.filter(student=student).order_by("-year_to_take", "university_faculty_id")

    context ={
        'nbar': 'student_detail',
        'student_id': student_id,
        'student_name': ' '.join([student.family_name, student.given_name]),
        'prev_student': prev_student,
        'next_student': next_student,
        'student_admission_exam_list': student_admission_exam_list,
    }
    return render(request, "admission_exam_db/student_detail.html", context)

@login_required
@user_passes_test(is_admin)
def upload_university_faculty(request):
    if request.method == "POST":
        form = UniversityFacultyCSVUploadForm(request.POST, request.FILES)
        if form.is_valid():
            csv_file = request.FILES['csv_file']
            decoded_file = csv_file.read().decode('utf-8-sig').splitlines()
            reader = csv.DictReader(decoded_file)
            for row in reader:
                university_faculty_code = row['university_faculty_code']
                university_name = row['university_name']
                faculty_name = row['faculty_name']
                department_name = row['department_name']
                display_name = row['display_name']
                faculty_system_midstream_name = row['faculty_system_midstream_name']
                faculty_system_field_code = row['faculty_system_field_code']
                faculty_system_field_name = row['faculty_system_field_name']

                # データモデルに保存
                UniversityFaculty.objects.update_or_create(
                    university_faculty_code=university_faculty_code,
                    defaults={
                        'university_name': university_name,
                        'university_faculty_code': university_faculty_code,
                        'university_name': university_name,
                        'faculty_name': faculty_name,
                        'department_name': department_name,
                        'display_name': display_name,
                        'faculty_system_midstream_name': faculty_system_midstream_name,
                        'faculty_system_field_code': faculty_system_field_code,
                        'faculty_system_field_name': faculty_system_field_name,
                    }
                )
            return redirect('admission_exam_db:upload_success') # アップロード成功画面にリダイレクト
    else:
        form = UniversityFacultyCSVUploadForm()
    context = {
        'nbar': 'upload_university_faculty',
        'form': form,
    }
    return render(request, 'admission_exam_db/upload_university_faculty.html', context)

@login_required
@user_passes_test(is_admin)
def download_template_csv(request, file_kind):
    filename = f"{file_kind}_template.csv"

    output = io.StringIO()
    writer = csv.writer(output, quoting=csv.QUOTE_MINIMAL)

    if file_kind == "university_faculty":
        writer.writerow(["university_faculty_code", "university_name", "faculty_name", "department_name", "display_name", "faculty_system_midstream_name", "faculty_system_field_code", "faculty_system_field_name"])
        writer.writerow(["10001" ,"旭川医科" ,"医" ,"医－前" ,"旭川医科_医_医－前" ,"医・歯・薬・保健" ,"5101" ,"医"])
    elif file_kind == "student":
        writer.writerow(["student_id", "homeroom_class", "attendance_number", "gender", "family_name", "given_name", "family_name_kana", "given_name_kana", "graduation_year"])
        writer.writerow(["1900123", "A", "01", "M", "佐藤", "花子", "さとう", "はなこ", "2025"])
    elif file_kind == "user":
        writer.writerow(["username", "password", "email"])
        writer.writerow(["test", "testpass", "test@example.ed.jp"])
    elif file_kind == "student_admission_exam":
        writer.writerow(["student_admission_exam_id", "student_id", "university_faculty_code", "year_to_take", "preference", "result"])
        writer.writerow(["30", "1990123", "10001", "2025", "A1", "AE"])

    # UTF-8-SIGにエンコード
    csv_data = output.getvalue().encode("utf-8-sig")
    output.close()

    response = HttpResponse(
        io.BytesIO(csv_data),
        content_type="text/csv",
        headers={"Content-Disposition": f'attachment; filename={filename}'},
    )
    
    return response

class Echo:# https://docs.djangoproject.com/ja/5.1/howto/outputting-csv/よりストリーミングCSVダウンロード用クラス ファイルオブジェクトのかわりに動作して、メモリを消費しない
    """An object that implements just the write method of the file-like
    interface.
    """

    def write(self, value):
        """Write the value by returning it, instead of storing in a buffer."""
        return value# 受け取った値をそのまま返すのでメモリを消費しない

@login_required
@user_passes_test(is_editor)
def download_data_csv(request, file_kind):
    filename = f"{file_kind}_data.csv"

    if file_kind == "student":
        student_list = Student.objects.order_by("homeroom_class", "attendance_number")

        header_row = [["student_id", "homeroom_class", "attendance_number", "gender", "family_name", "given_name", "family_name_kana", "given_name_kana", "graduation_year"]]

admission_exam_db/templates/admission_exam_db/admission_exam.html
{% extends 'admission_exam_db/base.html' %}
{% block title %}受験一覧{% endblock %}
{% block content %}
{% if admission_exam_list %}
    <input type="number" id="exam-year-filterInput" placeholder="受験年度" class="filterInput">
    <input type="number" id="graduation-year-filterInput" placeholder="卒業年" class="filterInput">
    <input type="text" id="university-name-filterInput" placeholder="大学名" class="filterInput">
    <input type="text" id="faculty-name-filterInput" placeholder="学部名" class="filterInput">
    <input type="text" id="student-name-filterInput" placeholder="氏名" class="filterInput">


    <!-- Modal -->
    <!-- モーダルを開くボタン -->
    <button class="modal-open js-modal-open">受験結果フィルター</button>

    <!-- モーダル本体 -->
    <div class="modal js-modal">
        <div class="modal-container">
            <!-- モーダルを閉じるボタン -->
            <div class="modal-close js-modal-close">×</div>
            <!-- モーダル内部のコンテンツ -->
            <div class="modal-content">
                <p>受験結果フィルター</p>
                <section class="passed-choices">
                    <section class="twocols">
                        <div class="twocols-container">
                            <div class="col left-col">
                                <ul>
                                    {% for choice in passed_choices %}
                                    <label><li><input type="checkbox" id={{ choice.key }} name="result-filter" class="passed-filterChoice result-filterChoice" value={{ choice.value }} checked >{{ choice.value }}</li></label>
                                    {% endfor %}
                                </ul>
                            </div>
                            <div class="col right-col">
                                <label><input type="checkbox" id="passed-choice" name="result-filter" value="P" checked >合格</label>
                            </div>
                        </div>
                    </section>
                </section>
                <section class="rejected-choices">
                    <section class="twocols">
                        <div class="twocols-container">
                            <div class="col left-col">
                                <ul>
                                    {% for choice in rejected_choices %}
                                    <label><li><input type="checkbox" id={{ choice.key }} name="result-filter" class="rejected-filterChoice result-filterChoice" value={{ choice.value }} checked >{{ choice.value }}</li></label>
                                    {% endfor %}
                                </ul>
                            </div>
                            <div class="col right-col">
                                <label><input type="checkbox" id="rejected-choice" name="result-filter" value="P" checked >不合格</label>
                            </div>
                        </div>
                    </section>
                </section>
                <section class="yet-choices">
                    <section class="twocols">
                        <div class="twocols-container">
                            <div class="col left-col">
                                <ul>
                                    {% for choice in yet_choices %}
                                    <label><li><input type="checkbox" id={{ choice.key }} name="result-filter" class="yet-filterChoice result-filterChoice" value={{ choice.value }} checked >{{ choice.value }}</li></label>
                                    {% endfor %}
                                </ul>
                            </div>
                            <div class="col right-col">
                                <label><input type="checkbox" id="yet-choice" name="result-filter" value="P" checked >未定</label>
                            </div>
                        </div>
                    </section>
                </section>
            </div>
        </div>
    </div>

    <table class="admission_exam_table table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>受験年度</th>
                <th>卒業年</th>
                <th>大学</th>
                <th>学部</th>
                <th>氏名</th>
                <th>結果</th>
            </tr>
        </thead>
        <tbody>
            {% for admission_exam in admission_exam_list %}
            <tr onclick="window.location.href='{% url 'admission_exam_db:edit_student_admission_exam' student_id=admission_exam.student.student_id student_admission_exam_id=admission_exam.id %}';" style="cursor:pointer;">
                <td class="exam_year">{{ admission_exam.year_to_take }}</td>
                <td class="graduation_year">{{ admission_exam.student.graduation_year }}</td>
                <td class="university">{{ admission_exam.university_faculty.university_name }}</td>
                <td class="faculty">{{ admission_exam.university_faculty.faculty_name }}</td>
                <td class="student_name">{{ admission_exam.student.family_name }} {{ admission_exam.student.given_name }}</td>
                <td class="result">{{ admission_exam.get_result_display }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% load static %}
    <script src="{% static 'admission_exam_db/js/admission_exam_filter.js' %}" defer></script>
{% else %}
    <p>No admission_exam data are available.</p>
{% endif %}
{% endblock %}

admission_exam_db/templates/admission_exam_db/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device=width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'admission_exam_db/css/style.css' %}" type="text/css">
    {% block head %}
    <!-- 子テンプレートがここにヘッダ要素を挿入する -->
    {% endblock %}
    <title>{% block title %}School Apps{% endblock %}</title>
</head>
<body>
    <!-- コンテンツ部分 -->
    <header>
        <div class="topnav">
            <a href="{% url 'admission_exam_db:index' %}" class="{% if nbar == 'home' %}active{% endif %}">ホーム</a>
            <a href="{% url 'admission_exam_db:student' %}" class="{% if nbar == 'student' %}active{% endif %}">生徒リスト</a>
            <a href="{% url 'admission_exam_db:admission_exam' %}" class="{% if nbar == 'admission_exam' %}active{% endif %}">受験リスト</a>
            <a href="{% url 'admission_exam_db:passed_exam_count' %}" class="{% if nbar == 'passed_exam_count' %}active{% endif %}">合格者数</a>
            <a href="{% url 'admission_exam_db:download_data' %}" class="{% if nbar == 'download_data' %}active{% endif %}">データダウンロード</a>
            {% if user.is_superuser %}
                <a href="{% url 'admission_exam_db:upload_university_faculty' %}" class="{% if nbar == 'upload_university_faculty' %}active{% endif %}">大学学部アップロード</a>
                <a href="{% url 'admission_exam_db:upload_student' %}" class="{% if nbar == 'upload_student' %}active{% endif %}">生徒アップロード</a>
                <a href="{% url 'admission_exam_db:upload_student_admission_exam' %}" class="{% if nbar == 'upload_student_admission_exam' %}active{% endif %}">受験アップロード</a>
                <a href="{% url 'admission_exam_db:upload_user' %}" class="{% if nbar == 'upload_user' %}active{% endif %}">ユーザアップロード</a>
            {% endif %}
            {% if user.is_authenticated %}
            <a href="{% url 'admission_exam_db:user' %}" class="{% if nbar == 'user' %}active{% endif %}">{{ user.username }}</a>
            {% else %}
                <a href="{% url 'admission_exam_db:login' %}" class="{% if nbar == 'login' %}active{% endif %}">ログイン</a>
            {% endif %}
        </div>
    </header>
    <main>
        {% block content %}
        <!-- 子テンプレートがここにコンテンツを挿入する -->
        {% endblock %}
    </main>
</body>
</html>

admission_exam_db/templates/admission_exam_db/download_data.html
{% extends 'admission_exam_db/base.html' %}
{% block title %}データダウンロード{% endblock %}
{% block content %}
<ul>
    <li><a href="{% url 'admission_exam_db:download_data_csv' file_kind='student' %}">生徒データダウンロード</a></li>
    <li><a href="{% url 'admission_exam_db:download_data_csv' file_kind='university_faculty' %}">大学学部データダウンロード</a></li>
    <li><a href="{% url 'admission_exam_db:download_data_csv' file_kind='student_admission_exam' %}">受験データダウンロード</a></li>
    <li><a href="{% url 'admission_exam_db:download_data_csv' file_kind='student_admission_exam_display' %}">受験データ（加工済み）ダウンロード</a></li>
    <li><a href="{% url 'admission_exam_db:download_data_csv' file_kind='preference_choice' %}">志望対応表ダウンロード</a></li>
    <li><a href="{% url 'admission_exam_db:download_data_csv' file_kind='result_choice' %}">結果対応表ダウンロード</a></li>
</ul>
{% endblock %}

admission_exam_db/templates/admission_exam_db/passed_exam_by_university.html
{% extends 'admission_exam_db/base.html' %}
{% block title %}受験一覧{% endblock %}
{% block content %}
{% if admission_exam_list %}
    <a href="{% url 'admission_exam_db:passed_exam_count' %}" class="Page-Btn">戻る</a>
    <h2>{{ exam_year }}年度 {{ university }}大学 合格者</h2>
    <table class="admission_exam_table table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>学部</th>
                <th>卒業年</th>
                <th>氏名</th>
                <th>結果</th>
            </tr>
        </thead>
        <tbody>
            {% for admission_exam in admission_exam_list %}
            <tr onclick="window.location.href='{% url 'admission_exam_db:edit_student_admission_exam' student_id=admission_exam.student.student_id student_admission_exam_id=admission_exam.id %}';" style="cursor:pointer;">
                <td class="faculty">{{ admission_exam.university_faculty.faculty_name }}</td>
                <td class="graduation_year">{{ admission_exam.student.graduation_year }}</td>
                <td class="student_name">{{ admission_exam.student.family_name }} {{ admission_exam.student.given_name }}</td>
                <td class="result">{{ admission_exam.get_result_display }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <p>No admission_exam data are available.</p>
{% endif %}
{% endblock %}

admission_exam_db/templates/admission_exam_db/student_detail.html
{% extends 'admission_exam_db/base.html' %}
{% block title %}{{ student_name }} 受験詳細{% endblock %}
{% block content %}
<h2>{{ student_name }} 受験詳細</h2>
{% if prev_student %}
    <a  href="{% url 'admission_exam_db:student_detail' student_id=prev_student.student_id %}">前の生徒</a>
{% endif %}
{% if next_student %}
    <a  href="{% url 'admission_exam_db:student_detail' student_id=next_student.student_id %}">次の生徒</a>
{% endif %}
{% if student_admission_exam_list %}
    <table class="student-admission-exam-table table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>大学_学部</th>
                <th>結果</th>
            </tr>
        </thead>
        <tbody>
            {% for admission_exam in student_admission_exam_list %}
            <tr onclick="window.location.href='{% url 'admission_exam_db:edit_student_admission_exam' student_id=admission_exam.student.student_id student_admission_exam_id=admission_exam.id %}';" style="cursor:pointer;">
                <td class="admission_exam_display_name">{{ admission_exam.university_faculty.display_name }}</td>
                <td class="admission_exam_result">{{ admission_exam.get_result_display }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <p>No admission exam data are available.</p>
{% endif %}
    <a href="{% url 'admission_exam_db:create_student_admission_exam' student_id=student_id %}">受験記録登録</a>
{% endblock %}

admission_exam_db/templates/admission_exam_db/upload_success.html
{% extends 'admission_exam_db/base.html' %}
{% block title %}アップロード成功{% endblock %}
{% block content %}
<p>アップロードが成功しました</p>
{% endblock %}